# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/omnilib/ufmt
    rev: v2.1.0
    hooks:
      - id: ufmt
        additional_dependencies:
          - black == 23.3.0
          - usort == 1.0.6
          - ufmt == 2.1.0
          - libcst == 1.0.1

# missing host field?
# -   repo: https://github.com/pre-commit/mirrors-clang-format
#     rev:  v17.0.5
#     hooks:
#       - id: clang-format
